services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      context: ./back
    container_name: backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started 
    environment:
      RUN_MODE: ${BACKEND_RUN_MODE-prod}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
    ports:
      - 8100:8000
    networks: 
      - backend

  nginx:
    image: nginx:1.29-alpine
    container_name: backend_nginx
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80 
    networks:
      - backend
  
  db:
    image: mysql:9.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: "%"
#    volumes:
#      - db:/etc/mysql/conf.d
    networks:
      - backend
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


networks:
  backend:

volumes:
  db:
