services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      context: ./back
    container_name: backend
    environment:
      RUN_MODE: ${BACKEND_RUN_MODE-prod}
    restart: unless-stopped
    ports:
      - 8100:8000
    networks: 
      - backend

  nginx:
    image: nginx:1.29-alpine
    container_name: backend_nginx
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started 
    ports:
      - 8001:80 
    networks:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


networks:
  backend:
