---
- name: Install NGINX
  become: yes
  become_method: sudo
  hosts: nginx1
  gather_facts: true
  roles:
    - nginx_install

- name: Install docker
  become: yes
  gather_facts: false
  hosts: nginx1
  roles:
    - docker_install


